In [8]:
include("lambda_cyclic.jl")

getRank (generic function with 1 method)

## Test computeLambda

In [9]:
test_lambda = lam = Dict([(5,0)=>-1, (5,1)=>1, (6,0)=>2, (6,1)=>-2, (4,1)=>0, (4,0)=>0])
test_triples = ([1,1,0], [0,0,0])
test_structure = [2]
## keys are (triple index, exponent index)
answers = Dict([(1,1)=>1, (2,1)=>-1, (1,2)=>-2, (2,2)=>2])

function testComputeLambda()
    for i in [1,2]
        for j in [1,2]
            if computeLambda(test_triples[i], basisExponents[j], test_lambda, test_structure) != answers[(i,j)]
                print("Error: triple", i, ", exponent", j)
            end
        end
    end
end

testComputeLambda()

## Test getLowerLambdaExp

In [10]:
getLowerLambdaExp(test_triples[2], test_lambda, test_structure)

1

## Test getGroupTriples

In [11]:
getValidGroupTriples([2,2])

16-element Vector{Vector{Vector{Int64}}}:
 [[0, 0], [0, 0], [0, 0]]
 [[1, 0], [1, 0], [0, 0]]
 [[0, 1], [0, 1], [0, 0]]
 [[1, 1], [1, 1], [0, 0]]
 [[1, 0], [0, 0], [1, 0]]
 [[0, 0], [1, 0], [1, 0]]
 [[1, 1], [0, 1], [1, 0]]
 [[0, 1], [1, 1], [1, 0]]
 [[0, 1], [0, 0], [0, 1]]
 [[1, 1], [1, 0], [0, 1]]
 [[0, 0], [0, 1], [0, 1]]
 [[1, 0], [1, 1], [0, 1]]
 [[1, 1], [0, 0], [1, 1]]
 [[0, 1], [1, 0], [1, 1]]
 [[1, 0], [0, 1], [1, 1]]
 [[0, 0], [1, 1], [1, 1]]

In [17]:
getGroupElements([2, 2])[1]

2-element Vector{Int64}:
 0
 0

In [22]:
etaIndex = [2, 3]
Int((Int(etaIndex[1] > etaIndex[2])-.5)*2)

-1

In [25]:
1 | 1

1

In [27]:
getGroupElements([3])

3-element Vector{Vector{Int64}}:
 [0]
 [1]
 [2]

In [30]:
validTriples = getValidGroupTriples([3])

9-element Vector{Vector{Vector{Int64}}}:
 [[0], [0], [0]]
 [[2], [1], [0]]
 [[1], [2], [0]]
 [[2], [0], [1]]
 [[1], [1], [1]]
 [[0], [2], [1]]
 [[1], [0], [2]]
 [[0], [1], [2]]
 [[2], [2], [2]]

In [34]:
G = validTriples[1]
g = G[1]
g == zeros(Int, 1)

true

In [36]:
collect(getGroupElements([2,2]))

2×2 Matrix{Vector{Int64}}:
 [0, 0]  [0, 1]
 [1, 0]  [1, 1]