In [1]:
struct TestGroup
    objVar::Int64
end

T = TestGroup(1)

TestGroup(1)

In [2]:
T.objVar

1

In [4]:
sum([[1,1], [1,-2]])

2-element Vector{Int64}:
  2
 -1

In [4]:
include("groups.jl")

groupAdd

In [5]:
Z2Z2 = FiniteCyclicGroup([2,2])

FiniteCyclicGroup([2, 2])

In [6]:
getNumFactors(Z2Z2)

2

In [7]:
groupElements = getGroupElements(Z2Z2)
groupElementTriples = [collect(T) for T in collect(Iterators.product(groupElements, groupElements, groupElements))];
sumZeroTriples = [T for T in groupElementTriples if groupAdd(Z2Z2, T) == zeros(4)];

In [8]:
test_triple = groupElementTriples[1]

3-element Vector{Vector{Int64}}:
 [0, 0]
 [0, 0]
 [0, 0]

In [9]:
sum(test_triple)

2-element Vector{Int64}:
 0
 0

In [10]:
groupAdd(Z2Z2, test_triple)

2-element Vector{Int64}:
 0
 0